on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        default: "16"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Running NodeJS workflow for repo ${{ github.repository }} (branch ${{ github.ref_name }})"
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.ref }}
    - run: npm ci
    - run: npm run test
    - run: npm run build
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: coverage/cobertura-coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '20 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ contains(fromJson('["development","staging","main"]'), github.ref_name) }}
    env:
      APPLICATION_NAME: "${{ github.repository }}"
      NODE_ENV: "${{ github.ref_name == 'main' && 'production' || github.ref_name }}"
    steps:
    - run: echo "Deploying NodeJS app $APPLICATION_NAME on environment $NODE_ENV"
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.ref }}
    - run: npm ci
    - run: npm run deploy
